version: '3.7'

services:

  backend:
    build:
      context: ./services/server
      dockerfile: Dockerfile-dev
    volumes:
      - './services/server:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=backend/server.py
      - FLASK_ENV=development
